version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword' # You can change this
      MYSQL_DATABASE: 'ailist'
      MYSQL_USER: 'ailist'
      MYSQL_PASSWORD: 'password' # You can change this
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'rootpassword' # Must match the db service's root password
    depends_on:
      - db

volumes:
  db_data:
